### ISSUE TITLE
Captured audio occasionally has phase issues

### ISSUE THREAD

**Issue by nostraightanswer** [bozbez/win-capture-audio#160] opened 2022-05-05 00:52 UTC
I tried this plugin for the first time on stream yesterday, and for basically everything but my Discord audio it worked fantastically, so thank you (and everyone contributing) for your efforts!

However, the Discord audio sometimes has notable phasing issues- or at least that's what it sounds like to me. Here's a [clip](https://clips.twitch.tv/ScrumptiousHilariousRhinocerosBudBlast-iFV7L0BYIOuyPoXd).
To me, it sounds like the voice chat audio is being captured twice but isn't synchronized perfectly, the offset causing the phasing issues I'm hearing. [Here's an example](https://soundcloud.com/nostraightanswer/win-capture-audio-double-audio-phasing-example/s-Y31qzRbWNHe?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing) I recorded and put together in FL Studio, which I feel supports my observation.

I've never submitted an issue on GitHub before, but I really love this plugin so far and I figured the worst that could happen is someone says "we know about it already" or something 😅 Hope this is helpful somehow at least.

**Comment by JaioCG** [comment] 2022-05-08 20:47
This has also happened for me on my streams in games like Portal 2 ([clip](https://clips.twitch.tv/SquareRealOrangeCeilingCat-Etaeb9uONDD9RnzZ)) and The Stanley Parable: Ultra Deluxe ([clip](https://clips.twitch.tv/BoxyKathishStarDBstyle-IA63-k36-t8DzMI_), so it's not just a Discord issue.

**Comment by nostraightanswer** [comment] 2022-05-08 23:56
> This has also happened for me on my streams in games like Portal 2 ([clip](https://clips.twitch.tv/SquareRealOrangeCeilingCat-Etaeb9uONDD9RnzZ)) and The Stanley Parable: Ultra Deluxe ([clip](https://clips.twitch.tv/BoxyKathishStarDBstyle-IA63-k36-t8DzMI_), so it's not just a Discord issue.

Got it. I'll adjust the title to reflect this! 👍

**Comment by JaioCG** [comment] 2022-05-15 19:26
Looking back at my personal setup, for the game audio I have in the clips in my previous comment, I had my win-capture-audio source set up to capture all except for Discord and Spotify, and when changing the setup to not include that, viewers have said the audio sounded better. So perhaps the issue may be Discord, even with excluding.

**Comment by bozbez** [comment] 2022-07-07 13:26
Duplicate of #126.

**Closed by bozbez** 2022-07-07 13:26 UTC
Labels: duplicate
