### ISSUE TITLE
Recording microphone when clicking "all except this window"

### ISSUE THREAD

**Issue by DweEroz** [bozbez/win-capture-audio#82] opened 2021-12-13 14:18 UTC
Hi!

First of all, your plugin is litteraly a game changer. Thank you so much ♥

I have spotted a quick problem though: the microphone is also captured when I click the box in order to record everything except a particular source. (Not sure about the EN translation since my OBS is in french, sorry in advance 😕)

For example, if I want to separate a single window from all the others, in order to change its audio volume independently from the rest of the PC, then the microphone will be split and recorded twice. I don't know if I am clear, but if I can help it is with pleasure!

The screen shows it better than I can explain 😄 :
![image](https://user-images.githubusercontent.com/49686576/145828186-28802c67-4f49-4272-ab38-94c5e74b71e4.png)

**Comment by Le-Iceberg** [comment] 2021-12-15 10:49
You have Voicemod or voicemeeter right? x)

**Comment by DweEroz** [comment] 2021-12-15 11:09
Owh, yes that's absolutely the problem that you have too on #56 😄 

Well, can't think of a turnaround, but at least you documented it so well than it can help bozbez a lot!

**Comment by Le-Iceberg** [comment] 2021-12-15 11:25
I'm french too, I specify that I write here in English for the ease of understanding communication.

The only solution I can advise you is to do as I did and not check this box 
create an "Audio Sources" scene 
![image](https://user-images.githubusercontent.com/47919634/146177597-41acd0d7-c073-4213-ac9f-9306aba07ce2.png)

create each source separately  

Add the "scene" source to your scene(s) (I know ... it's a lot more complicated for nothing ^^' it should really be an exclusion list rather than a unique exclusion....)
![image](https://user-images.githubusercontent.com/47919634/146177897-2390a86a-8c9f-4e97-91b1-34a3f2d4ef8b.png)

**Comment by bozbez** [comment] 2022-02-12 14:30
Duplicate of #56.

**Closed by bozbez** 2022-02-12 14:30 UTC
Labels: duplicate
