### ISSUE TITLE
Multiple instances as source seems to mix together

### ISSUE THREAD

**Issue by Ballantin** [bozbez/win-capture-audio#21] opened 2021-08-26 07:04 UTC
If I add, for example one instance as a source and capture FFXIV, and another instance as a source to capture Discord, the audio of the game goes to the Discord source output too.

**Comment by BuyMyMojo** [comment] 2021-08-28 04:30
I'll grab my windows version in a sec but as for reproducing it;
It was never consistent for me, some times it'd happen right away when set the one of the audio sources to a program and some times it took me some time to keep deselecting and reselecting the programs and alt tabbing to make it occur.

I'll also try to setup and windows 11 VM and see of I can reproduce the error there

**Comment by BuyMyMojo** [comment] 2021-08-28 05:57
![image](https://user-images.githubusercontent.com/46948241/131207993-875cba60-7ccf-4a2d-9687-39d08e6288cb.png)

**Comment by BuyMyMojo** [comment] 2021-08-28 07:34
![image](https://user-images.githubusercontent.com/46948241/131210370-8ba4e9ef-49cf-463c-8d97-d267b7d70e9d.png)
testing to see if it's a windows 10 issue soon

**Comment by BuyMyMojo** [comment] 2021-08-28 08:58
![image](https://user-images.githubusercontent.com/46948241/131212488-9b1047c9-c549-475d-b710-4d9bb752b96f.png)
Virtual box doesnt let you open OBS so here we go again because I know HyperV works

**Comment by BuyMyMojo** [comment] 2021-08-28 11:42
![image](https://user-images.githubusercontent.com/46948241/131216719-993080dc-8ec3-4ff8-a405-cbb29d034de1.png)
so it might just be a windows 10 isses, I havn't make the issues happen in windows 11 yet so you might need to have a toggle between both hooking methods. windows 11 mode marked as experimental on windows 10??

**Comment by BuyMyMojo** [comment] 2021-08-28 11:54
nope issue happens on windows 11 :(
that toggle still could be useful tho
![obs-win11](https://user-images.githubusercontent.com/46948241/131216936-498ab775-4f36-459e-ad77-2c4fa0ef4a72.gif)

**Comment by bozbez** [comment] 2021-09-02 13:26
[v2.0.0-beta.2](https://github.com/bozbez/win-capture-audio/releases/tag/v2.0.0-beta.2) _might_ help with this.

**Comment by BuyMyMojo** [comment] 2021-09-02 13:27
Current testing with v2.0.0-beta.2 shows no sign of the bug, will keep testing before closing

**Comment by Firehawke** [comment] 2021-09-03 09:11
I'm going to concur that it seems to be fixed after one night of testing. I, too, would prefer to go a bit longer before declaring it fixed, but things are definitely looking up.

**Comment by BuyMyMojo** [comment] 2021-09-03 10:50
it's looking good so far. I have been doing on and off testing through the day and still got nothing but I'll do more in-depth testing soon

**Closed** 2021-09-20 11:17 UTC
Labels: bug
