### ISSUE TITLE
Audiosource with "Capture every audiodata EXCEPT the selected window" not working when selected application not open.

### ISSUE THREAD

**Issue by ping-mee** [bozbez/win-capture-audio#58] opened 2021-11-04 07:26 UTC
Hi,
i found a (bug) feature that is kinda a problem. I selected in the settings of the application audio source a windows (Twitch Soundtrack) and clicked the checkmark for "Capture every audiodata EXCEPT the selected window". Now everything was working fine. It capured my desktopaudio without Twitch Soundtrack. But here is the problem: When you start OBS and the other application that you selected in your application audio source is not open the complete audio source is not working.

Can you please add a function that the source still working if the selected application is not open?

Hope you have a good day :)

**Comment by walker-WSH** [comment] 2021-12-28 05:34
steps:

1. run player1.exe and player2.exe
2. add win-audio source, select player2.exe, select checkbox "capture all except this process";
3. exit player2.exe and reboot OBS
4. check win-audio, there is no audio captured even player1.exe is playing audio

**Comment by bozbez** [comment] 2022-02-12 14:16
Duplicate of #34. Fixed via different method in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).

**Closed by bozbez** 2022-02-12 14:16 UTC
Labels: duplicate
