### ISSUE TITLE
[BUG]When the `Include process tree` unselected , it capture all the audio except select process  

### ISSUE THREAD

**Issue by shugen002** [bozbez/win-capture-audio#26] opened 2021-08-29 10:16 UTC
![image](https://user-images.githubusercontent.com/10257291/131246803-a443b809-87f3-43b4-9790-a598b3b05f12.png)

![image](https://user-images.githubusercontent.com/10257291/131246829-84b6f547-6b49-4399-bcf7-8f401b11a1a4.png)

![image](https://user-images.githubusercontent.com/10257291/131246894-eb749277-ebe0-4a51-9eff-f8b98009f0c6.png)

A process should not have audio output , right ?

When the `Include process tree` unselected , it capture all the audio except select process .

WIndows 11 ,  22000.168

-------------------

I am using [EarTrumpet](https://github.com/File-New-Project/EarTrumpet) to display audio output status . And it may give you some idea about how to get audio output app list.

-----------------

`Include process tree` does not capture audio output by grandson process, but child process. Please document that.

**Comment by bozbez** [comment] 2021-08-29 12:26
That's the intended behaviour, I just named the option badly. Will be fixed soon.

The issue with enumerating the audio sessions directly (with `IAudioSessionEnumerator`) is that the user might want to target a process that has not yet opened its audio session - in particular Chrome only creates it when you open a page outputting audio. The window selection logic works pretty well currently, so not planning on changing that until at least #21 is solved.

Will add something about the grandson processes (or rather just remove the `process tree` wording).

**Closed by bozbez** 2021-08-29 12:26 UTC
